// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBji8M60AfcIs14o0RVp0swoJD19y-GFvM',
    appId: '1:853225013562:web:c8c04e6f9b2e639779d003',
    messagingSenderId: '853225013562',
    projectId: 'pblif-2f656',
    authDomain: 'pblif-2f656.firebaseapp.com',
    storageBucket: 'pblif-2f656.appspot.com',
    measurementId: 'G-3FDDXFSL7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg4rwe0DzAZeSCxo7Muu_tKSm7GH79hOo',
    appId: '1:853225013562:android:1c2463bc465df19b79d003',
    messagingSenderId: '853225013562',
    projectId: 'pblif-2f656',
    storageBucket: 'pblif-2f656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzm2P8zv7GJ7KsEgb7lQOYD6M077Xb93I',
    appId: '1:853225013562:ios:b34d75665dd203d679d003',
    messagingSenderId: '853225013562',
    projectId: 'pblif-2f656',
    storageBucket: 'pblif-2f656.appspot.com',
    iosClientId: '853225013562-0k737vvnnd4hotd0b8a4ctv2vg4b3koh.apps.googleusercontent.com',
    iosBundleId: 'com.example.nov',
  );
}
